from cx_Freeze import setup, Executable
import os
from datetime import date


# delete the previous database:
db_path = 'lwt/LingL_database.sqlite3'
if os.path.exists(db_path):
    os.remove(db_path)

# first creating the database and populate it
os.system('python manage.py migrate')
os.system('python manage.py loaddata  initial_fixture_USER.yaml')
os.system('python manage.py loaddata  initial_fixture_LANGUAGES.yaml')

cwd = os.getcwd()
lingl_image_path = os.path.join(cwd,'lwt','static','lwt','img','site_icon_16x16.png')
# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(
        packages = [
            'lxml',
            'LingL',
            'LingL.settings',
            'LingL.urls',
            'LingL.wsgi',
            '__future__',
            '_ast',
            '_bisect',
            '_blake2',
            '_bootlocale',
            '_bz2',
            '_codecs',
            '_collections',
            '_collections_abc',
            '_compat_pickle',
            '_compression',
            '_ctypes',
            '_datetime',
            '_functools',
            '_hashlib',
            '_heapq',
            '_imp',
            '_io',
            '_json',
            '_locale',
            '_lzma',
            '_markupbase',
            '_opcode',
            '_operator',
            '_pickle',
            '_posixsubprocess',
            '_pydecimal',
            '_random',
            '_sha3',
            '_signal',
            '_socket',
            '_sqlite3',
            '_sre',
            #'_ssl',
            '_stat',
            '_string',
            '_struct',
            '_thread',
            '_warnings',
            '_weakref',
            '_weakrefset',
            'abc',
            'allauth',
            'allauth.account',
            'allauth.account.adapter',
            'allauth.account.admin',
            'allauth.account.app_settings',
            'allauth.account.apps',
            'allauth.account.auth_backends',
            'allauth.account.forms',
            'allauth.account.managers',
            'allauth.account.migrations',
            'allauth.account.migrations.0001_initial',
            'allauth.account.migrations.0002_email_max_length',
            'allauth.account.models',
            'allauth.account.signals',
            'allauth.account.templatetags',
            'allauth.account.templatetags.account',
            'allauth.account.urls',
            'allauth.account.utils',
            'allauth.account.views',
            'allauth.app_settings',
            'allauth.exceptions',
            'allauth.models',
            'allauth.socialaccount',
            'allauth.socialaccount.adapter',
            'allauth.socialaccount.admin',
            'allauth.socialaccount.app_settings',
            'allauth.socialaccount.apps',
            'allauth.socialaccount.fields',
            'allauth.socialaccount.forms',
            'allauth.socialaccount.helpers',
            'allauth.socialaccount.migrations',
            'allauth.socialaccount.migrations.0001_initial',
            'allauth.socialaccount.migrations.0002_token_max_lengths',
            'allauth.socialaccount.migrations.0003_extra_data_default_dict',
            'allauth.socialaccount.models',
            'allauth.socialaccount.providers',
            'allauth.socialaccount.providers.base',
            'allauth.socialaccount.signals',
            'allauth.socialaccount.templatetags',
            'allauth.socialaccount.templatetags.socialaccount',
            'allauth.socialaccount.urls',
            'allauth.socialaccount.views',
            'allauth.urls',
            'allauth.utils',
            'argparse',
            'ast',
            'atexit',
            'base64',
            'bdb',
            'binascii',
            'bisect',
            'builtins',
            'bz2',
            'calendar',
            'cgi',
            'cmd',
            'code',
            'codecs',
            'codeop',
            'collections',
            'collections.abc',
            'contextlib',
            'copy',
            'copyreg',
            'crispy_forms',
            'crispy_forms.base',
            'crispy_forms.bootstrap',
            'crispy_forms.exceptions',
            'crispy_forms.helper',
            'crispy_forms.layout',
            'crispy_forms.layout_slice',
            'crispy_forms.templatetags',
            'crispy_forms.templatetags.crispy_forms_field',
            'crispy_forms.templatetags.crispy_forms_filters',
            'crispy_forms.templatetags.crispy_forms_tags',
            'crispy_forms.templatetags.crispy_forms_utils',
            'crispy_forms.utils',
            'ctypes',
            'ctypes._endian',
            'ctypes.util',
            'datetime',
            'decimal',
            'difflib',
            'dis',
            'django',
            'django.apps',
            'django.apps.config',
            'django.apps.registry',
            'django.conf',
            'django.conf.global_settings',
            'django.conf.locale',
            'django.conf.locale.en',
            'django.conf.locale.en.formats',
            'django.conf.urls',
            'django.conf.urls.static',
            'django.contrib',
            'django.contrib.admin',
            'django.contrib.admin.actions',
            'django.contrib.admin.apps',
            'django.contrib.admin.checks',
            'django.contrib.admin.decorators',
            'django.contrib.admin.exceptions',
            'django.contrib.admin.filters',
            'django.contrib.admin.helpers',
            'django.contrib.admin.migrations',
            'django.contrib.admin.migrations.0001_initial',
            'django.contrib.admin.migrations.0002_logentry_remove_auto_add',
            'django.contrib.admin.models',
            'django.contrib.admin.options',
            'django.contrib.admin.sites',
            'django.contrib.admin.templatetags',
            'django.contrib.admin.templatetags.admin_urls',
            'django.contrib.admin.utils',
            'django.contrib.admin.views',
            'django.contrib.admin.views.main',
            'django.contrib.admin.widgets',
            'django.contrib.auth',
            'django.contrib.auth.admin',
            'django.contrib.auth.apps',
            'django.contrib.auth.backends',
            'django.contrib.auth.base_user',
            'django.contrib.auth.checks',
            'django.contrib.auth.context_processors',
            'django.contrib.auth.decorators',
            'django.contrib.auth.forms',
            'django.contrib.auth.hashers',
            'django.contrib.auth.management',
            'django.contrib.auth.middleware',
            'django.contrib.auth.migrations',
            'django.contrib.auth.migrations.0001_initial',
            'django.contrib.auth.migrations.0002_alter_permission_name_max_length',
            'django.contrib.auth.migrations.0003_alter_user_email_max_length',
            'django.contrib.auth.migrations.0004_alter_user_username_opts',
            'django.contrib.auth.migrations.0005_alter_user_last_login_null',
            'django.contrib.auth.migrations.0006_require_contenttypes_0002',
            'django.contrib.auth.migrations.0007_alter_validators_add_error_messages',
            'django.contrib.auth.migrations.0008_alter_user_username_max_length',
            'django.contrib.auth.models',
            'django.contrib.auth.password_validation',
            'django.contrib.auth.signals',
            'django.contrib.auth.tokens',
            'django.contrib.auth.validators',
            'django.contrib.auth.views',
            'django.contrib.contenttypes',
            'django.contrib.contenttypes.admin',
            'django.contrib.contenttypes.apps',
            'django.contrib.contenttypes.checks',
            'django.contrib.contenttypes.fields',
            'django.contrib.contenttypes.forms',
            'django.contrib.contenttypes.management',
            'django.contrib.contenttypes.migrations',
            'django.contrib.contenttypes.migrations.0001_initial',
            'django.contrib.contenttypes.migrations.0002_remove_content_type_name',
            'django.contrib.contenttypes.models',
            'django.contrib.contenttypes.views',
            'django.contrib.humanize',
            'django.contrib.messages',
            'django.contrib.messages.api',
            'django.contrib.messages.apps',
            'django.contrib.messages.constants',
            'django.contrib.messages.context_processors',
            'django.contrib.messages.middleware',
            'django.contrib.messages.storage',
            'django.contrib.messages.storage.base',
            'django.contrib.messages.storage.cookie',
            'django.contrib.messages.storage.fallback',
            'django.contrib.messages.storage.session',
            'django.contrib.messages.utils',
            'django.contrib.sessions',
            'django.contrib.sessions.apps',
            'django.contrib.sessions.backends',
            'django.contrib.sessions.backends.base',
            'django.contrib.sessions.backends.db',
            'django.contrib.sessions.base_session',
            'django.contrib.sessions.exceptions',
            'django.contrib.sessions.middleware',
            'django.contrib.sessions.migrations',
            'django.contrib.sessions.migrations.0001_initial',
            'django.contrib.sessions.models',
            'django.contrib.sessions.serializers',
            'django.contrib.sites',
            'django.contrib.sites.admin',
            'django.contrib.sites.apps',
            'django.contrib.sites.management',
            'django.contrib.sites.migrations',
            'django.contrib.sites.migrations.0001_initial',
            'django.contrib.sites.migrations.0002_alter_domain_unique',
            'django.contrib.sites.models',
            'django.contrib.sites.requests',
            'django.contrib.sites.shortcuts',
            'django.contrib.staticfiles',
            'django.contrib.staticfiles.apps',
            'django.contrib.staticfiles.finders',
            'django.contrib.staticfiles.handlers',
            'django.contrib.staticfiles.management',
            'django.contrib.staticfiles.management.commands',
            'django.contrib.staticfiles.management.commands.runserver',
            'django.contrib.staticfiles.storage',
            'django.contrib.staticfiles.utils',
            'django.contrib.staticfiles.views',
            'django.core',
            'django.core.cache',
            'django.core.cache.backends',
            'django.core.cache.backends.base',
            'django.core.cache.backends.locmem',
            'django.core.cache.utils',
            'django.core.checks',
            'django.core.checks.caches',
            'django.core.checks.compatibility',
            'django.core.checks.database',
            'django.core.checks.messages',
            'django.core.checks.model_checks',
            'django.core.checks.registry',
            'django.core.checks.security',
            'django.core.checks.security.base',
            'django.core.checks.security.csrf',
            'django.core.checks.security.sessions',
            'django.core.checks.templates',
            'django.core.checks.urls',
            'django.core.exceptions',
            'django.core.files',
            'django.core.files.base',
            'django.core.files.images',
            'django.core.files.locks',
            'django.core.files.move',
            'django.core.files.storage',
            'django.core.files.temp',
            'django.core.files.uploadedfile',
            'django.core.files.uploadhandler',
            'django.core.files.utils',
            'django.core.handlers',
            'django.core.handlers.base',
            'django.core.handlers.exception',
            'django.core.handlers.wsgi',
            'django.core.mail',
            'django.core.mail.message',
            'django.core.mail.utils',
            'django.core.management',
            'django.core.management.base',
            'django.core.management.color',
            'django.core.management.commands',
            'django.core.management.commands.runserver',
            'django.core.paginator',
            'django.core.serializers',
            'django.core.serializers.base',
            'django.core.serializers.json',
            'django.core.serializers.python',
            'django.core.servers',
            'django.core.servers.basehttp',
            'django.core.signals',
            'django.core.signing',
            'django.core.validators',
            'django.core.wsgi',
            'django.db',
            'django.db.backends',
            'django.db.backends.base',
            'django.db.backends.base.base',
            'django.db.backends.base.client',
            'django.db.backends.base.creation',
            'django.db.backends.base.features',
            'django.db.backends.base.introspection',
            'django.db.backends.base.operations',
            'django.db.backends.base.schema',
            'django.db.backends.base.validation',
            'django.db.backends.signals',
            'django.db.backends.sqlite3',
            'django.db.backends.sqlite3.base',
            'django.db.backends.sqlite3.client',
            'django.db.backends.sqlite3.creation',
            'django.db.backends.sqlite3.features',
            'django.db.backends.sqlite3.introspection',
            'django.db.backends.sqlite3.operations',
            'django.db.backends.sqlite3.schema',
            'django.db.backends.utils',
            'django.db.migrations',
            'django.db.migrations.exceptions',
            'django.db.migrations.executor',
            'django.db.migrations.graph',
            'django.db.migrations.loader',
            'django.db.migrations.migration',
            'django.db.migrations.operations',
            'django.db.migrations.operations.base',
            'django.db.migrations.operations.fields',
            'django.db.migrations.operations.models',
            'django.db.migrations.operations.special',
            'django.db.migrations.recorder',
            'django.db.migrations.state',
            'django.db.models',
            'django.db.models.aggregates',
            'django.db.models.base',
            'django.db.models.constants',
            'django.db.models.deletion',
            'django.db.models.expressions',
            'django.db.models.fields',
            'django.db.models.fields.files',
            'django.db.models.fields.proxy',
            'django.db.models.fields.related',
            'django.db.models.fields.related_descriptors',
            'django.db.models.fields.related_lookups',
            'django.db.models.fields.reverse_related',
            'django.db.models.functions',
            'django.db.models.functions.datetime',
            'django.db.models.indexes',
            'django.db.models.lookups',
            'django.db.models.manager',
            'django.db.models.options',
            'django.db.models.query',
            'django.db.models.query_utils',
            'django.db.models.signals',
            'django.db.models.sql',
            'django.db.models.sql.compiler',
            'django.db.models.sql.constants',
            'django.db.models.sql.datastructures',
            'django.db.models.sql.query',
            'django.db.models.sql.subqueries',
            'django.db.models.sql.where',
            'django.db.models.utils',
            'django.db.transaction',
            'django.db.utils',
            'django.dispatch',
            'django.dispatch.dispatcher',
            'django.forms',
            'django.forms.boundfield',
            'django.forms.fields',
            'django.forms.forms',
            'django.forms.formsets',
            'django.forms.models',
            'django.forms.renderers',
            'django.forms.utils',
            'django.forms.widgets',
            'django.http',
            'django.http.cookie',
            'django.http.multipartparser',
            'django.http.request',
            'django.http.response',
            'django.middleware',
            'django.middleware.cache',
            'django.middleware.clickjacking',
            'django.middleware.common',
            'django.middleware.csrf',
            'django.middleware.security',
            'django.shortcuts',
            'django.template',
            'django.template.backends',
            'django.template.backends.base',
            'django.template.backends.django',
            'django.template.base',
            'django.template.context',
            'django.template.context_processors',
            'django.template.defaultfilters',
            'django.template.defaulttags',
            'django.template.engine',
            'django.template.exceptions',
            'django.template.library',
            'django.template.loader',
            'django.template.loader_tags',
            'django.template.loaders',
            'django.template.loaders.app_directories',
            'django.template.loaders.base',
            'django.template.loaders.filesystem',
            'django.template.response',
            'django.template.smartif',
            'django.template.utils',
            'django.templatetags',
            'django.templatetags.cache',
            'django.templatetags.i18n',
            'django.templatetags.l10n',
            'django.templatetags.static',
            'django.templatetags.tz',
            'django.urls',
            'django.urls.base',
            'django.urls.exceptions',
            'django.urls.resolvers',
            'django.urls.utils',
            'django.utils',
            'django.utils._os',
            'django.utils.autoreload',
            'django.utils.baseconv',
            'django.utils.cache',
            'django.utils.crypto',
            'django.utils.datastructures',
            'django.utils.dateformat',
            'django.utils.dateparse',
            'django.utils.dates',
            'django.utils.datetime_safe',
            'django.utils.deconstruct',
            'django.utils.decorators',
            'django.utils.deprecation',
            'django.utils.duration',
            'django.utils.encoding',
            'django.utils.formats',
            'django.utils.functional',
            'django.utils.html',
            'django.utils.http',
            'django.utils.inspect',
            'django.utils.ipv6',
            'django.utils.itercompat',
            'django.utils.log',
            'django.utils.lorem_ipsum',
            'django.utils.module_loading',
            'django.utils.numberformat',
            'django.utils.regex_helper',
            'django.utils.safestring',
            'django.utils.termcolors',
            'django.utils.text',
            'django.utils.timesince',
            'django.utils.timezone',
            'django.utils.translation',
            'django.utils.translation.trans_real',
            'django.utils.tree',
            'django.utils.version',
            'django.views',
            'django.views.debug',
            'django.views.decorators',
            'django.views.decorators.cache',
            'django.views.decorators.csrf',
            'django.views.decorators.debug',
            'django.views.generic',
            'django.views.generic.base',
            'django.views.generic.dates',
            'django.views.generic.detail',
            'django.views.generic.edit',
            'django.views.generic.list',
            'django.views.i18n',
            'django.views.static',
            'email',
            'email._encoded_words',
            'email._header_value_parser',
            'email._parseaddr',
            'email._policybase',
            'email.base64mime',
            'email.charset',
            'email.contentmanager',
            'email.encoders',
            'email.errors',
            'email.feedparser',
            'email.generator',
            'email.header',
            'email.headerregistry',
            'email.iterators',
            'email.message',
            'email.mime',
            'email.mime.base',
            'email.mime.message',
            'email.mime.multipart',
            'email.mime.nonmultipart',
            'email.mime.text',
            'email.parser',
            'email.policy',
            'email.quoprimime',
            'email.utils',
            'encodings',
            'encodings.aliases',
            'encodings.idna',
            'encodings.latin_1',
            'encodings.utf_8',
            'enum',
            'errno',
            'fcntl',
            'fnmatch',
            'functools',
            'genericpath',
            'getpass',
            'gettext',
            'glob',
            'grp',
            'gzip',
            'hashlib',
            'heapq',
            'hmac',
            'html',
            'html.entities',
            'html.parser',
            'http',
            'http.client',
            'http.cookies',
            'http.server',
            'importlib',
            'importlib._bootstrap',
            'importlib._bootstrap_external',
            'importlib.abc',
            'importlib.machinery',
            'importlib.util',
            'inspect',
            'io',
            'ipaddress',
            'itertools',
            'json',
            'json.decoder',
            'json.encoder',
            'json.scanner',
            'keyword',
            'linecache',
            'locale',
            'logging',
            'logging.config',
            'logging.handlers',
            'lwt',
            'lwt.admin',
            'lwt.constants',
            'lwt.forms',
            'lwt.migrations',
            'lwt.models',
            'lwt.templatetags',
            'lwt.templatetags.debug',
            'lwt.templatetags.djangoversion',
            'lwt.templatetags.pythonversion',
            'lwt.templatetags.range',
            'lwt.views',
#             'lwt.views._import_oldlwt',
            'lwt.views._nolang_redirect_decorator',
            'lwt.views._setting_cookie_db',
            'lwt.views._utilities_views',
            'lwt.views.backuprestore',
            'lwt.views.export2anki_exporter',
            'lwt.views.homepage',
            'lwt.views.language',
            'lwt.views.statistics',
            'lwt.views.term',
            'lwt.views.term_list',
            'lwt.views.termform',
            'lwt.views.text',
            'lwt.views.text_read',
            'lzma',
            'marshal',
            'math',
            'mathfilters',
            'mathfilters.templatetags',
            'mathfilters.templatetags.mathfilters',
            'mimetypes',
            'numbers',
            'opcode',
            'operator',
            'os',
            #'pdb',
            'pickle',
            'pkgutil',
            'platform',
            'posix',
            'posixpath',
            'pprint',
            'pwd',
            'pytz',
            'pytz.exceptions',
            'pytz.lazy',
            'pytz.tzfile',
            'pytz.tzinfo',
            'queue',
            'quopri',
            'random',
            're',
            'reprlib',
            'select',
            'selectors',
            'setuptools',
            'shutil',
            'signal',
            'site',
            'six',
            'socket',
            'socketserver',
            'splitjson',
            'splitjson.fields',
            'splitjson.widgets',
            'sqlite3',
            'sqlite3.dbapi2',
            'sre_compile',
            'sre_constants',
            'sre_parse',
            #'ssl',
            'stat',
            'string',
            'stringprep',
            'struct',
            'subprocess',
            'sys',
            'tags_input',
            'tags_input.admin',
            'tags_input.exceptions',
            'tags_input.fields',
            'tags_input.urls',
            'tags_input.utils',
            'tags_input.views',
            'tags_input.widgets',
            'tempfile',
            'termios',
            'textwrap',
            'threading',
            'time',
            'token',
            'tokenize',
            'traceback',
            'types',
            'unicodedata',
            'urllib',
            'urllib.error',
            'urllib.parse',
            'urllib.request',
            'urllib.response',
            'uu',
            'uuid',
            'waitress',
            'warnings',
            'weakref',
            'wsgiref',
            'wsgiref.handlers',
            'wsgiref.headers',
            'wsgiref.simple_server',
            'wsgiref.util',
            'zipimport',
            'zlib',
#             '__main__',
#             '_frozen_importlib',
#             '_frozen_importlib_external',
#             'allauth.compat',
#             'crispy_forms.compatibility',
#             'dj-static',
#             'django.contrib.admin.templatetags.admin_list',
#             'django.contrib.admin.templatetags.admin_modify',
#             'django.contrib.admin.templatetags.admin_static',
#             'django.contrib.admin.templatetags.log',
#             'django.contrib.staticfiles.templatetags',
#             'django.contrib.staticfiles.templatetags.staticfiles',
#             'django.core.checks.compatibility.django_1_10',
#             'django.core.checks.compatibility.django_1_8_0',
#             'django.core.checks.utils',
#             'django.core.urlresolvers',
#             'django.db.models.functions.base',
#             'django.utils.html_parser',
#             'django.utils.lru_cache',
#             'django.utils.six',
#             'django.utils.six.moves',
#             'django.utils.six.moves.http_client',
#             'django.utils.six.moves.urllib',
#             'django.utils.six.moves.urllib.parse',
#             'django.utils.six.moves.urllib.request',
#             'django.utils.synch',
#             'lwt.migrations.0001_initial',
#             'lwt.migrations.0002_auto_20171108_1355',
#             'lwt.migrations.0003_auto_20171108_2042',
#             'lwt.migrations.0004_auto_20171109_1924',
#             'lwt.migrations.0005_auto_20171109_2019',
#             'lwt.migrations.0006_auto_20171109_2113',
#             'lwt.migrations.0007_auto_20171110_1124',
#             'lwt.migrations.0008_texts_lastopentime',
#             'lwt.migrations.0009_auto_20171113_2130',
#             'lwt.migrations.0010_auto_20171113_2130',
#             'lwt.migrations.0011_settings_currentfilter_text_settings_currentfilter_word',
#             'lwt.migrations.0012_settings_selected_words',
#             'lwt.migrations.0013_auto_20171126_1128',
#             'lwt.migrations.0014_auto_20171126_1129',
#             'lwt.migrations.0015_words_export2anki',
#             'lwt.migrations.0016_auto_20171126_1325',
#             'lwt.migrations.0017_auto_20171129_1603',
#             'lwt.migrations.0018_words_extra_field',
#             'lwt.migrations.0019_auto_20171202_1319',
#             'lwt.migrations.0020_texts_archived_txt',
#             'lwt.migrations.0021_languages_extra_field_key',
#             'lwt.migrations.0022_auto_20171203_1931',
#             'lwt.migrations.0023_remove_texts_archived_txt',
#             'os.path',
#             'sitecustomize',
                'wx',
                'fitz',
            ], 
        excludes = ['tkinter', 'Tkinter','yappi', 'line-converter'],
        include_files = [
              'LingL_app.ico',
              'LingL_app.icns',
#                 'appversion.txt',
                #('./libcrypt.so.2', 'libcrypt.so.2'),
#                 os.path.join('lwt', 'LingL_database.sqlite3'), #no need, it's automatically joined
#                 os.path.join('templates','allauth'),
                ],
        )

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('LingL_app.py', base=base, icon=lingl_image_path, target_name='LingLibre')
]

# define the appversion and save it:
today = date.today().strftime("%Y.%m.%d")
appversiontxt_path = os.path.join(os.getcwd(), 'lwt','appversion.txt')
with open(appversiontxt_path, 'w', encoding="utf8") as appversion_f:
    appversion_f.write(today)


setup(name='LingL',
      version = today,
      description = 'Learn languages by reading what you want!',
      options = dict(build_exe = buildOptions),
      executables = executables)
