# Generated by Django 3.2.4 on 2021-07-14 07:58

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lwt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('origin_lang_code', models.CharField(max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', lwt.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Extra_field_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extra_field_key',
                'unique_together': {('title', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Grouper_of_same_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id_string', models.CharField(max_length=500, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Grouper_of_same_words',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('dicturi', models.TextField(default='https://glosbe.com/gapi/translate?from=eng&&dest=•••&&format=json, https://en.wiktionary.org/wiki/###')),
                ('dict1uri', models.CharField(blank=True, max_length=200, null=True)),
                ('dict2uri', models.CharField(blank=True, max_length=200, null=True)),
                ('googletranslateuri', models.CharField(blank=True, default='*http://translate.google.com/?ie=UTF-8&sl=en&tl=••&text=###', max_length=200, null=True)),
                ('exporttemplate', models.CharField(blank=True, default='$status<br>$language<br>$text<br><h1>$word</h1>\t<h1>$translation</h1><br>$romanization<br>$sentence<br>$customsentence<br>$compoundword<br>$similarword\\<br>$extrafieldn', max_length=1000, null=True)),
                ('textsize', models.IntegerField(default=150)),
                ('charactersubstitutions', models.CharField(default="´='|`='|’='|‘='|...=…|..=‥", max_length=500)),
                ('regexpsplitsentences', models.CharField(default='.!?:;', max_length=500)),
                ('exceptionssplitsentences', models.CharField(default='(?<=Mr)\\.|(?<=Dr)\\.|(?<=[A-Z])\\.|(?<=Vd)\\.|(?<=Vds)\\.', max_length=500)),
                ('regexpwordcharacters', models.CharField(default='a-zA-ZÀ-ÖØ-öø-ȳ', max_length=500)),
                ('removespaces', models.BooleanField(default=False)),
                ('spliteachchar', models.BooleanField(default=False)),
                ('righttoleft', models.BooleanField(default=False)),
                ('has_romanization', models.BooleanField(default=False)),
                ('code_639_1', models.CharField(blank=True, max_length=2, null=True)),
                ('code_639_2t', models.CharField(blank=True, max_length=3, null=True)),
                ('code_639_2b', models.CharField(blank=True, max_length=3, null=True)),
                ('django_code', models.CharField(blank=True, max_length=8, null=True)),
                ('extra_field_key', models.ManyToManyField(related_name='languagehavingthisextrafieldkey', to='lwt.Extra_field_key')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'languages',
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('sentencetext', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lwt.languages')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('annotatedtext', models.TextField()),
                ('audiouri', models.CharField(blank=True, max_length=200, null=True)),
                ('sourceuri', models.CharField(blank=True, max_length=1000, null=True)),
                ('lastopentime', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('wordcount', models.IntegerField(blank=True, default=0, null=True)),
                ('wordcount_distinct', models.IntegerField(blank=True, default=0, null=True)),
                ('contenttype', models.CharField(blank=True, choices=[('text', 'text'), ('doc', 'doc'), ('html', 'html')], default='text', max_length=4, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texthavingthislanguage', to='lwt.languages')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Wordtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('wotagtext', models.CharField(max_length=20)),
                ('wotagcomment', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wordtags',
                'unique_together': {('wotagtext', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('textOrder', models.IntegerField(blank=True, null=True)),
                ('wordtext', models.CharField(blank=True, max_length=250, null=True)),
                ('wordtextLC', models.CharField(blank=True, max_length=250, null=True)),
                ('isnotword', models.BooleanField(default=False)),
                ('translation', models.CharField(blank=True, max_length=500, null=True)),
                ('romanization', models.CharField(blank=True, max_length=100, null=True)),
                ('customsentence', models.CharField(blank=True, max_length=1000, null=True)),
                ('wordinside_order', models.TextField(blank=True, max_length=250, null=True)),
                ('wordinside_order_NK', models.TextField(blank=True, max_length=250, null=True)),
                ('isCompoundword', models.BooleanField(default=False)),
                ('show_compoundword', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=False)),
                ('extra_field', models.TextField(blank=True, max_length=500, null=True)),
                ('webpagesection', models.IntegerField(default=0)),
                ('compoundword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compoundwordhavingthiswordinside', to='lwt.words')),
                ('grouper_of_same_words', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouper_of_same_words_for_this_word', to='lwt.grouper_of_same_words')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordhavingthislanguage', to='lwt.languages')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_having_this_word', to='lwt.sentences')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texthavingthisword', to='lwt.texts')),
                ('wordtags', models.ManyToManyField(related_name='wordtag_with_this_word', to='lwt.Wordtags')),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='Uploaded_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_text', models.FileField(blank=True, upload_to='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Texttags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('txtagtext', models.CharField(max_length=20)),
                ('txtagcomment', models.CharField(default='', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'texttags',
                'unique_together': {('txtagtext', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='texts',
            name='texttags',
            field=models.ManyToManyField(related_name='texthavingthistag', to='lwt.Texttags'),
        ),
        migrations.CreateModel(
            name='Settings_texts_per_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=10)),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=9999)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_text_visit_statuses_via_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('stdft', models.IntegerField(default=0)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_text_r_frameheight_percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=50)),
                ('min', models.IntegerField(default=5)),
                ('max', models.IntegerField(default=95)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_text_l_framewidth_percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=50)),
                ('min', models.IntegerField(default=5)),
                ('max', models.IntegerField(default=95)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_text_h_frameheight_with_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=200)),
                ('min', models.IntegerField(default=10)),
                ('max', models.IntegerField(default=999)),
                ('isinteger', models.BooleanField(default='True')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_text_h_frameheight_no_audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=140)),
                ('min', models.IntegerField(default=10)),
                ('max', models.IntegerField(default=999)),
                ('isinteger', models.BooleanField(default='True')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_test_sentence_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('stdft', models.IntegerField(default=1)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_test_r_frameheight_percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=50)),
                ('min', models.IntegerField(default=5)),
                ('max', models.IntegerField(default=95)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_test_main_frame_waiting_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=9999)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_test_l_framewidth_percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=50)),
                ('min', models.IntegerField(default=5)),
                ('max', models.IntegerField(default=95)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_test_h_frameheight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=140)),
                ('min', models.IntegerField(default=10)),
                ('max', models.IntegerField(default=999)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_test_edit_frame_waiting_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=500)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=99999999)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_terms_per_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=100)),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=9999)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_term_translation_delimiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('stdft', models.CharField(default='/;|', max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_term_sentence_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('stdft', models.IntegerField(default=1)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_tags_per_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=100)),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=9999)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_similar_terms_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=9)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_show_text_word_counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('stdft', models.IntegerField(default=1)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_show_all_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('stdft', models.IntegerField(default=0)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_selected_rows_nb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('currently_selected_rows_nb', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_selected_rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('possible_selected_rows', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_origin_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_mobile_display_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('stdft', models.IntegerField(default=0)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentwordstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentwordsort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentwordquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentwordpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currenttextsort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currenttextquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currenttextpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currenttext_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentlang_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentlang_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentfilter_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filterwordforthisword', to='lwt.words')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentfilter_texttag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('texttag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtertagforthistexttag', to='lwt.texttags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentfilter_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtertextforthistext', to='lwt.texts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentfilter_lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filterlangforthislanguage', to='lwt.languages')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sentences',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lwt.texts'),
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_file_name', models.CharField(blank=True, max_length=255)),
                ('restore_file', models.FileField(blank=True, upload_to='')),
                ('import_oldlwt', models.FileField(blank=True, upload_to='')),
                ('import_lingq', models.FileField(blank=True, upload_to='')),
                ('import_readlang', models.FileField(blank=True, upload_to='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='texts',
            unique_together={('title', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='sentences',
            unique_together={('text', 'order', 'owner')},
        ),
    ]
