# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivedtexts',
            fields=[
                ('atid', models.AutoField(db_column='AtID', primary_key=True, serialize=False)),
                ('atlgid', models.IntegerField(db_column='AtLgID')),
                ('attitle', models.CharField(db_column='AtTitle', max_length=200)),
                ('attext', models.TextField(db_column='AtText')),
                ('atannotatedtext', models.TextField(db_column='AtAnnotatedText')),
                ('ataudiouri', models.CharField(blank=True, db_column='AtAudioURI', max_length=200, null=True)),
                ('atsourceuri', models.CharField(blank=True, db_column='AtSourceURI', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'archivedtexts',
            },
        ),
        migrations.CreateModel(
            name='Archtexttags',
            fields=[
                ('agatid', models.IntegerField(db_column='AgAtID', primary_key=True, serialize=False)),
                ('agt2id', models.IntegerField(db_column='AgT2ID')),
            ],
            options={
                'db_table': 'archtexttags',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('lgid', models.AutoField(db_column='LgID', primary_key=True, serialize=False)),
                ('lgname', models.CharField(db_column='LgName', max_length=40, unique=True)),
                ('lgdict1uri', models.CharField(db_column='LgDict1URI', max_length=200)),
                ('lgdict2uri', models.CharField(blank=True, db_column='LgDict2URI', max_length=200, null=True)),
                ('lggoogletranslateuri', models.CharField(blank=True, db_column='LgGoogleTranslateURI', max_length=200, null=True)),
                ('lgexporttemplate', models.CharField(blank=True, db_column='LgExportTemplate', max_length=1000, null=True)),
                ('lgtextsize', models.IntegerField(db_column='LgTextSize')),
                ('lgcharactersubstitutions', models.CharField(db_column='LgCharacterSubstitutions', max_length=500)),
                ('lgregexpsplitsentences', models.CharField(db_column='LgRegexpSplitSentences', max_length=500)),
                ('lgexceptionssplitsentences', models.CharField(db_column='LgExceptionsSplitSentences', max_length=500)),
                ('lgregexpwordcharacters', models.CharField(db_column='LgRegexpWordCharacters', max_length=500)),
                ('lgremovespaces', models.IntegerField(db_column='LgRemoveSpaces')),
                ('lgspliteachchar', models.IntegerField(db_column='LgSplitEachChar')),
                ('lgrighttoleft', models.IntegerField(db_column='LgRightToLeft')),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Lwtgeneral',
            fields=[
                ('lwtkey', models.CharField(db_column='LWTKey', max_length=40, primary_key=True, serialize=False)),
                ('lwtvalue', models.CharField(blank=True, db_column='LWTValue', max_length=40, null=True)),
            ],
            options={
                'db_table': '_lwtgeneral',
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('seid', models.AutoField(db_column='SeID', primary_key=True, serialize=False)),
                ('selgid', models.IntegerField(db_column='SeLgID')),
                ('setxid', models.IntegerField(db_column='SeTxID')),
                ('seorder', models.IntegerField(db_column='SeOrder')),
                ('setext', models.TextField(blank=True, db_column='SeText', null=True)),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('stkey', models.CharField(db_column='StKey', max_length=40, primary_key=True, serialize=False)),
                ('stvalue', models.CharField(blank=True, db_column='StValue', max_length=40, null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tgid', models.AutoField(db_column='TgID', primary_key=True, serialize=False)),
                ('tgtext', models.CharField(db_column='TgText', max_length=20, unique=True)),
                ('tgcomment', models.CharField(db_column='TgComment', max_length=200)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Tags2',
            fields=[
                ('t2id', models.AutoField(db_column='T2ID', primary_key=True, serialize=False)),
                ('t2text', models.CharField(db_column='T2Text', max_length=20, unique=True)),
                ('t2comment', models.CharField(db_column='T2Comment', max_length=200)),
            ],
            options={
                'db_table': 'tags2',
            },
        ),
        migrations.CreateModel(
            name='Textitems',
            fields=[
                ('tiid', models.AutoField(db_column='TiID', primary_key=True, serialize=False)),
                ('tilgid', models.IntegerField(db_column='TiLgID')),
                ('titxid', models.IntegerField(db_column='TiTxID')),
                ('tiseid', models.IntegerField(db_column='TiSeID')),
                ('tiorder', models.IntegerField(db_column='TiOrder')),
                ('tiwordcount', models.IntegerField(db_column='TiWordCount')),
                ('titext', models.CharField(db_column='TiText', max_length=250)),
                ('titextlc', models.CharField(db_column='TiTextLC', max_length=250)),
                ('tiisnotword', models.IntegerField(db_column='TiIsNotWord')),
            ],
            options={
                'db_table': 'textitems',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('txid', models.AutoField(db_column='TxID', primary_key=True, serialize=False)),
                ('txlgid', models.IntegerField(db_column='TxLgID')),
                ('txtitle', models.CharField(db_column='TxTitle', max_length=200)),
                ('txtext', models.TextField(db_column='TxText')),
                ('txannotatedtext', models.TextField(db_column='TxAnnotatedText')),
                ('txaudiouri', models.CharField(blank=True, db_column='TxAudioURI', max_length=200, null=True)),
                ('txsourceuri', models.CharField(blank=True, db_column='TxSourceURI', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Texttags',
            fields=[
                ('tttxid', models.IntegerField(db_column='TtTxID', primary_key=True, serialize=False)),
                ('ttt2id', models.IntegerField(db_column='TtT2ID')),
            ],
            options={
                'db_table': 'texttags',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('woid', models.AutoField(db_column='WoID', primary_key=True, serialize=False)),
                ('wolgid', models.IntegerField(db_column='WoLgID')),
                ('wotext', models.CharField(db_column='WoText', max_length=250)),
                ('wotextlc', models.CharField(db_column='WoTextLC', max_length=250)),
                ('wostatus', models.IntegerField(db_column='WoStatus')),
                ('wotranslation', models.CharField(db_column='WoTranslation', max_length=500)),
                ('woromanization', models.CharField(blank=True, db_column='WoRomanization', max_length=100, null=True)),
                ('wosentence', models.CharField(blank=True, db_column='WoSentence', max_length=1000, null=True)),
                ('wocreated', models.DateTimeField(db_column='WoCreated')),
                ('wostatuschanged', models.DateTimeField(db_column='WoStatusChanged')),
                ('wotodayscore', models.FloatField(db_column='WoTodayScore')),
                ('wotomorrowscore', models.FloatField(db_column='WoTomorrowScore')),
                ('worandom', models.FloatField(db_column='WoRandom')),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='Wordtags',
            fields=[
                ('wtwoid', models.IntegerField(db_column='WtWoID', primary_key=True, serialize=False)),
                ('wttgid', models.IntegerField(db_column='WtTgID')),
            ],
            options={
                'db_table': 'wordtags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wordtags',
            unique_together=set([('wtwoid', 'wttgid')]),
        ),
        migrations.AlterUniqueTogether(
            name='words',
            unique_together=set([('wolgid', 'wotextlc')]),
        ),
        migrations.AlterUniqueTogether(
            name='texttags',
            unique_together=set([('tttxid', 'ttt2id')]),
        ),
        migrations.AlterUniqueTogether(
            name='archtexttags',
            unique_together=set([('agatid', 'agt2id')]),
        ),
    ]
