# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texthavingthislanguage', to='lwt.Languages'),
        ),
        migrations.AlterField(
            model_name='words',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordhavingthislanguage', to='lwt.Languages'),
        ),
    ]
