# Generated by Django 3.2.4 on 2021-06-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texthavingthisword', to='lwt.texts'),
        ),
    ]
