# Generated by Django 3.2 on 2021-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='has_romanization',
            field=models.BooleanField(default=False),
        ),
    ]
