# Generated by Django 3.2.3 on 2021-05-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0002_settings_selected_rows_nb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_selected_rows',
            name='selected_rows',
        ),
    ]
