# Generated by Django 3.2.4 on 2021-08-08 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0002_equiv_oldlwtid_linglid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equiv_oldlwtid_linglid',
            new_name='Equiv_word_oldlwtid_linglid',
        ),
        migrations.CreateModel(
            name='Equiv_wordtag_oldlwtid_linglid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldlwtid', models.IntegerField()),
                ('linglid_or_nk', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
