# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0002_auto_20171108_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings_currentwordtag2',
            new_name='Settings_Currentfilter_lang_id',
        ),
        migrations.RenameModel(
            old_name='Settings_currentwordtag1',
            new_name='Settings_Currentfilter_wordtag_id',
        ),
        migrations.RemoveField(
            model_name='settings_currentarchivepage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings_currentarchivequery',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings_currentarchivetexttag1',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings_currentarchivetexttag12',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings_currentarchivetexttag2',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings_currentwordtag12',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Settings_currentarchivepage',
        ),
        migrations.DeleteModel(
            name='Settings_currentarchivequery',
        ),
        migrations.DeleteModel(
            name='Settings_currentarchivetexttag1',
        ),
        migrations.DeleteModel(
            name='Settings_currentarchivetexttag12',
        ),
        migrations.DeleteModel(
            name='Settings_currentarchivetexttag2',
        ),
        migrations.DeleteModel(
            name='Settings_currentwordtag12',
        ),
    ]
