# Generated by Django 3.2 on 2021-05-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0002_auto_20210511_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='words',
            unique_together={('text_order', 'text', 'owner')},
        ),
    ]
