# Generated by Django 3.2 on 2021-05-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0003_alter_words_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='text_order',
            new_name='textOrder',
        ),
        migrations.AlterUniqueTogether(
            name='words',
            unique_together={('textOrder', 'text', 'owner')},
        ),
    ]
