# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0003_auto_20171108_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_currentfilter_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_filter', models.BooleanField(default=True)),
                ('strong', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterlangforthislanguage', to='lwt.Languages')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='settings_archivedtexts_per_page',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings_currentfilter_lang_id',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Settings_archivedtexts_per_page',
        ),
        migrations.DeleteModel(
            name='Settings_Currentfilter_lang_id',
        ),
    ]
