# Generated by Django 3.2.4 on 2021-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0003_auto_20210606_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='wordcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='texts',
            name='wordcount_distinct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
