# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0004_auto_20171109_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_currentfilter_lang',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filterlangforthislanguage', to='lwt.Languages'),
        ),
    ]
