# Generated by Django 3.2.4 on 2021-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0004_auto_20210606_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
