# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0005_auto_20171109_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings_currentfilter_lang',
            old_name='is_filter',
            new_name='is_strong',
        ),
        migrations.RemoveField(
            model_name='settings_currentfilter_lang',
            name='strong',
        ),
    ]
