# Generated by Django 3.2 on 2021-05-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0005_alter_words_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_having_this_word', to='lwt.sentences'),
        ),
    ]
