# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0006_auto_20171109_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_currentfilter_texttag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('texttag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtertagforthistexttag', to='lwt.Texttags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='settings_currentfilter_wordtag_id',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Settings_Currentfilter_wordtag_id',
        ),
    ]
