# Generated by Django 3.2.4 on 2021-06-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0006_auto_20210616_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='webpage_section',
            field=models.IntegerField(default=0),
        ),
    ]
