# Generated by Django 3.2.4 on 2021-06-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0007_words_webpage_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='webpage_section',
            new_name='webpagesection',
        ),
    ]
