# Generated by Django 3.2 on 2021-05-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0007_restore_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouper_of_same_words',
            old_name='translation',
            new_name='id_string',
        ),
    ]
