# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0007_auto_20171110_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='lastopentime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
