# Generated by Django 3.2.4 on 2021-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0008_rename_webpage_section_words_webpagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
