# Generated by Django 3.2 on 2021-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0008_rename_translation_grouper_of_same_words_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='wordinside_order_NK',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
