# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0009_auto_20171113_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='compoundword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compoundwordhavingthiswordinside', to='lwt.Words'),
        ),
    ]
