# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0010_auto_20171113_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_currentfilter_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtertextforthistext', to='lwt.Texts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings_currentfilter_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('is_strong', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filterwordforthisword', to='lwt.Words')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
