# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0011_settings_currentfilter_text_settings_currentfilter_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_selected_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stvalue', models.CharField(blank=True, max_length=40, null=True)),
                ('stdft', models.CharField(blank=True, default='', max_length=40)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('isinteger', models.BooleanField(default='False')),
                ('possible_selected_words', models.TextField()),
                ('selected_words', models.TextField(default='[]')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
