# Generated by Django 3.2.4 on 2021-06-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0011_uploaded_text_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texts',
            name='is_webpage',
        ),
        migrations.AddField(
            model_name='texts',
            name='contenttype',
            field=models.CharField(choices=[('text', 'text'), ('pdf', 'pdf'), ('html', 'html')], default='text', max_length=4),
        ),
    ]
