# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0012_settings_selected_words'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings_selected_words',
            new_name='Settings_selected_rows',
        ),
    ]
