# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0013_auto_20171126_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings_selected_rows',
            old_name='possible_selected_words',
            new_name='possible_selected_rows',
        ),
        migrations.RenameField(
            model_name='settings_selected_rows',
            old_name='selected_words',
            new_name='selected_rows',
        ),
    ]
