# Generated by Django 3.2.4 on 2021-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0013_alter_texts_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='restore',
            name='import_lingq',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='grouper_of_same_words',
            name='id_string',
            field=models.CharField(max_length=500),
        ),
    ]
