# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0014_auto_20171126_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='export2anki',
            field=models.BooleanField(default=False),
        ),
    ]
