# Generated by Django 3.2.4 on 2021-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0014_auto_20210708_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouper_of_same_words',
            name='id_string',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
