# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0015_words_export2anki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='export2anki',
            new_name='state',
        ),
    ]
