# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0016_auto_20171126_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='exporttemplate',
            field=models.CharField(blank=True, default='$status<br>$language<br>$text<br><h1>$word</h1>\t<h1>$translation</h1><br>$romanization<br>$sentence<br>$customsentence<br>$compoundword<br>$similarword\n', max_length=1000, null=True),
        ),
    ]
