# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0017_auto_20171129_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='extra_field',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
