# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0018_words_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languages',
            name='exporttemplate',
            field=models.CharField(blank=True, default='$status<br>$language<br>$text<br><h1>$word</h1>\t<h1>$translation</h1><br>$romanization<br>$sentence<br>$customsentence<br>$compoundword<br>$similarword\\<br>$extrafieldn', max_length=1000, null=True),
        ),
    ]
