# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0019_auto_20171202_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='archived_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
