# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0020_texts_archived_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='extra_field_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
