# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0021_languages_extra_field_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_field_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extra_field_key',
            },
        ),
        migrations.RemoveField(
            model_name='languages',
            name='extra_field_key',
        ),
        migrations.AddField(
            model_name='languages',
            name='extra_field_key',
            field=models.ManyToManyField(related_name='languagehavingthisextrafieldkey', to='lwt.Extra_field_key'),
        ),
    ]
