# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwt', '0022_auto_20171203_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texts',
            name='archived_txt',
        ),
    ]
